# Copyright (c) 2021-2022 by Marc Feeley, All Rights Reserved.
# Copyright (c) 2021-2022 by Marc-André Bélanger, All Rights Reserved.

herefromlib = _ffi/python
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = python\#.scm
MODULES_SCM = python.scm
MAIN_MODULES = python
OTHER_RCFILES =

include $(libfromhere)/module-common.mk
