# Copyright (c) 2021-2022 by Marc Feeley, All Rights Reserved.
# Copyright (c) 2021-2022 by Marc-André Bélanger, All Rights Reserved.

herefromlib = _ffi
libfromhere = ..
SUBDIRS = python
HEADERS_SCM =
MODULES_SCM =
MAIN_MODULES =
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
